[package]
name = "shared-kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
rust_decimal = { version = "1", features = ["serde"] }
thiserror = "2"
uuid = { version = "1", features = ["v4", "serde", "js"] }

[dev-dependencies]
pretty_assertions = "1"
rust_decimal_macros = "1"
